apiVersion: v1
kind: Service
metadata:
  name: web-srv
spec:
  selector:
    app: myweb
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  annotations:
    kubernetes.io/change-cause: "myweb v1"
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 10%
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec:
      containers:  
      - name: myweb
        image: ino99/myweb-k8s:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: web-srv
          servicePort: 6000
